name: build-toolchain

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git .
          git fetch --prune --unshallow
          git checkout $GITHUB_REF

      - name: Run build.sh in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            -e GITHUB_ACTIONS="${{ env.GITHUB_ACTIONS }}" \
            -e GITHUB_ACTOR="${{ env.GITHUB_ACTOR }}" \
            -e GITHUB_REPOSITORY="${{ env.GITHUB_REPOSITORY }}" \
            -e GITHUB_REF="${{ env.GITHUB_REF }}" \
            -e GITHUB_SHA="${{ env.GITHUB_SHA }}" \
            -e GITHUB_RUN_ID="${{ env.GITHUB_RUN_ID }}" \
            -e GITHUB_RUN_NUMBER="${{ env.GITHUB_RUN_NUMBER }}" \
            -e GITHUB_JOB="${{ env.GITHUB_JOB }}" \
            ubuntu:latest \
            /bin/bash -c "./build.sh"
