name: build-toolchain

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: ./build.sh
