jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build.sh in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            -e GITHUB_ACTIONS="${{ env.GITHUB_ACTIONS }}" \
            -e GITHUB_ACTOR="${{ env.GITHUB_ACTOR }}" \
            -e GITHUB_REPOSITORY="${{ env.GITHUB_REPOSITORY }}" \
            -e GITHUB_REF="${{ env.GITHUB_REF }}" \
            -e GITHUB_SHA="${{ env.GITHUB_SHA }}" \
            -e GITHUB_RUN_ID="${{ env.GITHUB_RUN_ID }}" \
            -e GITHUB_RUN_NUMBER="${{ env.GITHUB_RUN_NUMBER }}" \
            -e GITHUB_JOB="${{ env.GITHUB_JOB }}" \
            ubuntu:latest \
            /bin/bash -c "./build.sh"
